config/routes.rb
Rails.application.routes.draw do
  root 'cupcakes#index'
  resources :cupcakes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cupcake.rb
class Cupcake < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cupcakes_controller.rb
class CupcakesController < ApplicationController
  before_action :set_cupcake, only: [:show, :edit, :update, :destroy]

  # GET /cupcakes
  # GET /cupcakes.json
  def index
    @cupcakes = Cupcake.all
  end

  # GET /cupcakes/1
  # GET /cupcakes/1.json
  def show
  end

  # GET /cupcakes/new
  def new
    @cupcake = Cupcake.new
  end

  # GET /cupcakes/1/edit
  def edit
  end

  # POST /cupcakes
  # POST /cupcakes.json
  def create
    @cupcake = Cupcake.new(cupcake_params)

    respond_to do |format|
      if @cupcake.save
        format.html { redirect_to @cupcake, notice: 'Cupcake was successfully created.' }
        format.json { render :show, status: :created, location: @cupcake }
      else
        format.html { render :new }
        format.json { render json: @cupcake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cupcakes/1
  # PATCH/PUT /cupcakes/1.json
  def update
    respond_to do |format|
      if @cupcake.update(cupcake_params)
        format.html { redirect_to @cupcake, notice: 'Cupcake was successfully updated.' }
        format.json { render :show, status: :ok, location: @cupcake }
      else
        format.html { render :edit }
        format.json { render json: @cupcake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cupcakes/1
  # DELETE /cupcakes/1.json
  def destroy
    @cupcake.destroy
    respond_to do |format|
      format.html { redirect_to cupcakes_url, notice: 'Cupcake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cupcake
      @cupcake = Cupcake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cupcake_params
      params.require(:cupcake).permit(:flavor, :quantity, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cupcakes_helper.rb
module CupcakesHelper
end

app/views/cupcakes/_form.html.erb
<%= form_for(cupcake) do |f| %>
  <% if cupcake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cupcake.errors.count, "error") %> prohibited this cupcake from being saved:</h2>

      <ul>
      <% cupcake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cupcakes/edit.html.erb
<h1>Editing Cupcake</h1>

<%= render 'form', cupcake: @cupcake %>

<%= link_to 'Show', @cupcake %> |
<%= link_to 'Back', cupcakes_path %>

app/views/cupcakes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Cupcakes</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cupcakes.each do |cupcake| %>
      <tr>
        <td><%= cupcake.flavor %></td>
        <td><%= cupcake.quantity %></td>
        <td><%= cupcake.price %></td>
        <td><%= link_to 'Show', cupcake %></td>
        <td><%= link_to 'Edit', edit_cupcake_path(cupcake) %></td>
        <td><%= link_to 'Destroy', cupcake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cupcake', new_cupcake_path %>

app/views/cupcakes/new.html.erb
<h1>New Cupcake</h1>

<%= render 'form', cupcake: @cupcake %>

<%= link_to 'Back', cupcakes_path %>

app/views/cupcakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @cupcake.flavor %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cupcake.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cupcake.price %>
</p>

<%= link_to 'Edit', edit_cupcake_path(@cupcake) %> |
<%= link_to 'Back', cupcakes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstHerokuApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>